#####CODING THE MUSIC FOR THE GAME
###using GERARDO's helpful discussion 
###https://downloads.khinsider.com/game-soundtracks/album/sen-amiga
###THE song is called "shrill (title screen)"



####after creating an account and attempting to download the music, the website asked for a donation

## i later found this website:
# https://gamethemesongs.com/T2_The_Arcade_Game_-_Analyzing_Performance.html

###I will now be using the music: 
# T2 The Arcade Game - Analyzing Performance for our game

## the music is very techno-like and goes well with our game

##temporarily commenting this code (7:25)

# # import pygame
# # pygame.init()
# # pygame.mixer.init()
# # BG_Music = pygame.mixer.Sound('audio/MusicFile.GAME MUSIC')
# # BG_Music.play(-1)

# # pygame.mixer.music.load("music.mp3") 
# # pygame.mixer.music.play(-1,0.0)
###I have been experimenting with this code, and the error that i keep getting is "unable to open the file"

### I will now go on youtube to try to figure out the problem 

###I Think i have to download the pygame mixer, but i am not sure if it is a library or not

##code based off of 
##https://www.youtube.com/watch?v=D1V3xx4kBmA

import pygame
pygame.init()
pygame.mixer.init()
pygame.mixer.music.Sound("Song.mp3")
pygame.mixer.music.play(-1)


###i got the code to work
### the problem i was having, was the "song" file was not in the same file as the code in which i was running

### A MESSAGE TO GABE
##, Gabe just copy and paste this into the final game, 
##i can send you the song download, download it and put it in the same file
##the code will then work 

